spring.application.name=inventory
server.port=8080

spring.datasource.url=jdbc:postgresql://ep-sweet-dream-ap1t7pum-pooler.c-7.us-east-1.aws.neon.tech/inventory_db
spring.datasource.username=rontiowner
spring.datasource.password=npg_xgPkWStJT4z0
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
